### ISSUE TITLE
Application closing problem.

### ISSUE THREAD

**Issue by kryyltkn** [ParetoSecurity/pareto-updater-mac#11]
The app finds the update and downloads it. But during installation the app closes by itself and won't install. I have tested this with many app updates and I am using the latest version.

Screen recording:
https://we.tl/t-Mu7DNdEFsq

**Comment by kryyltkn** [comment]
[Uploading Ekran Kaydı 2024-04-30 00.57.11.mov.zip…]()

**Comment by zupo** [comment]
Thank you for a detailed report, we're looking into it.

**Comment by dz0ny** [comment]
Resolved in https://github.com/ParetoSecurity/pareto-updater-mac/releases/tag/1.1.40

**Comment by kryyltkn** [comment]
Hello. Thank you very much for your support.
