### ISSUE TITLE
Updater not picking up needed updates that app complains about

### ISSUE THREAD

**Issue by zupo** [ParetoSecurity/pareto-updater-mac#3]
Pareto Security app is complaining about Zoom being out of date. Updater is running, but not showing in MenuBar that I need to update Zoom.
<img width="883" alt="Screenshot 2022-05-25 at 15 13 35" src="https://user-images.githubusercontent.com/311580/170283533-70ee69a2-fd54-46fe-9dc4-6d54b30cdd8d.png">

**Comment by dz0ny** [comment]
Zoom is curently not supported.
