### ISSUE TITLE
Says there is an update for an application that is up to date 

### ISSUE THREAD

**Issue by StrangeRanger** [ParetoSecurity/pareto-updater-mac#4]
Pareto Updater says that there is a new version of [QLMarkdown](https://github.com/sbarex/QLMarkdown), when I already have the latest version installed. 
<img width="272" alt="Screen Shot 2022-07-21 at 1 58 10 PM" src="https://user-images.githubusercontent.com/30395560/180209108-fffcdbfe-61b5-4dac-ab4c-64cb368c53de.png">
<img width="292" alt="Screen Shot 2022-07-21 at 1 58 30 PM" src="https://user-images.githubusercontent.com/30395560/180209112-43df5562-089d-491f-9662-c5b73669dad1.png">
<img width="421" alt="Screen Shot 2022-07-21 at 1 58 39 PM" src="https://user-images.githubusercontent.com/30395560/180209113-ed89adf1-4ed1-4357-b328-dbceeae7cb85.png">

When having Pareto Updater update the application, it downloads an older version of the application.
<img width="447" alt="Screen Shot 2022-07-21 at 2 00 38 PM" src="https://user-images.githubusercontent.com/30395560/180209292-63071068-af87-41c5-85d4-8a951247fc02.png">
`

**Comment by StrangeRanger** [comment]
And it still says that there is a newer version even after having Pareto Updater update the application.
<img width="251" alt="Screen Shot 2022-07-21 at 2 05 26 PM" src="https://user-images.githubusercontent.com/30395560/180209526-02a58120-c304-4693-844a-e606c9167c92.png">

**Comment by zupo** [comment]
Hey @StrangeRanger, thanks for reporting this!

**Comment by dz0ny** [comment]
This due to the https://sbarex.github.io/QLMarkdown/appcast.xml having all kinds of version formats, sometimes even duplicate. Will issue a fix that will detect such cases.

**Comment by StrangeRanger** [comment]
@dz0ny I'm not sure if the commit fixed the problem. It's still doing the same thing. And yes, I am using Version 1.0.48 - 47 of Pareto Updater.

**Comment by dz0ny** [comment]
Cache was set a bit too lean, and in your case it was/is still resolving cached information. The next release has a fix that will properly address it.

**Comment by StrangeRanger** [comment]
Oh, ok. That makes sense.
