### ISSUE TITLE
No latest version for application is given

### ISSUE THREAD

**Issue by StrangeRanger** [ParetoSecurity/pareto-updater-mac#5]
Where Pareto Updater displays the latest version of an application, [WiFiSpoof](https://wifispoof.com/) doesn't list it's latest version. It is instead listed as `Latest: 0.0.0`. WiFiSpoof can be downloaded via the macOS App Store or from WiFiSpoof's website. I currently have the latter (website version) installed, so I'm unsure if this issue would be present if I had the App Store version. 
<img width="149" alt="Screen Shot 2022-07-21 at 4 11 17 PM" src="https://user-images.githubusercontent.com/30395560/180236030-66da22fd-8752-4877-bf57-b448f74350f3.png">

**Comment by zupo** [comment]
Thanks for the report, we'll look into it!
