### ISSUE TITLE
[Question] No longer checks for App Store updates

### ISSUE THREAD

**Issue by StrangeRanger** [ParetoSecurity/pareto-updater-mac#6]
Not sure if this would be better suited for the "Discussions" tab, but I had a question. I noticed in one of the previous updates, Pareto Updater was set to no longer check for updates in the App Store. Is this going to be reverted in a later version, or is there no plan for Pareto Updater to check for updates for apps installed via the App Store?

**Comment by dz0ny** [comment]
The Updater never had functionality to check for App Store installs, that would require hacking in with private APIs. What was added was check to not overwrite apps that are distributed both in the App Store and via vendor site to not create confusion of "why my app was overwritten with something else". Hope this explains it :)

**Comment by StrangeRanger** [comment]
Oh, I see. Thanks for explaining.
