### ISSUE TITLE
Does not correctly parse certain version strings

### ISSUE THREAD

**Issue by luckman212** [ParetoSecurity/pareto-updater-mac#8]
Seems like Pareto Updater only parses digits and decimals, not spaces, parens, hyphens etc. Maybe that's a violation of Apple's `CFBundleShortVersionString` format. Not sure on that.

In any case, this is the result (both of the apps below are already up-to-date):

![image](https://user-images.githubusercontent.com/1992842/191816789-88459ea6-056f-4412-91cf-0f1219265cab.png)

**Comment by zupo** [comment]
Thanks, will have a look!

**Comment by dz0ny** [comment]
This was resolved in the latest release.

**Comment by luckman212** [comment]
Confirmed! Working great. 🚀

**Comment by luckman212** [comment]
Nice- but there's still a small problem with CloudMounter. I already have 3.11(698) installed...

![5cb760001478e4f8b79b4308cec6e570338f42cf](https://user-images.githubusercontent.com/1992842/192528988-aca83f9e-694e-4ffc-8a94-99636f5c847b.png)

```shell
$ for v in CFBundleShortVersionString CFBundleVersion; do /usr/libexec/PlistBuddy -c "Print :$v" /Applications/CloudMounter.app/Contents/Info.plist; done
3.11
698
```
