### ISSUE TITLE
Menubar icon is always white

### ISSUE THREAD

**Issue by marianstiehler** [ParetoSecurity/pareto-updater-mac#9]
The menu bar icon is always white, even in light mode.
<img width="74" alt="Bildschirmfoto 2022-10-02 um 11 55 19" src="https://user-images.githubusercontent.com/18249424/193448364-e08141bc-04f3-42bc-8ae2-6583f0bf6d29.png">

**Comment by zupo** [comment]
Thanks for the bug report, we'll take a look and report back.

**Comment by dz0ny** [comment]
Fixed in https://github.com/ParetoSecurity/pareto-updater-mac/releases/tag/1.1.18

**Comment by marianstiehler** [comment]
Terrific! Works now. Thank you.
